name: Integration

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']

jobs:
  halogen:
    name: Halogen
 
    runs-on: ubuntu-latest

    steps:
      - name: Notify of change
        run: |
          curl -X POST https://api.github.com/repos/nsaunders/purescript-tecton-halogen/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_ACCESS_TOKEN }} \
          --data '{"event_type": "dependency_changed", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
